name: image-syncer-build

on:
  push:
    branches: github-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - name: build image-syncer
        run: |
          make cmd
      - name: Assemble Artifact
        id: assemble_artifact
        env:
          TZ: Asia/Shanghai
        run: |
          time=$(date +%Y%m%d%H%M)
          release_tag=$time
          echo "##[set-output name=release_tag;]$release_tag"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        with:
          files: image-syncer
          tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}

